[package]
name = "amber"
version = "0.1.5"
authors = ["Michael Snoyman <michael@snoyman.com>"]
edition = "2018"
description = "Manage secret values in-repo via public key cryptography"
readme = "README.md"
homepage = "https://github.com/fpco/amber"
repository = "https://github.com/fpco/amber"
license = "MIT"
keywords = ["continuous-integration", "secrets", "encryption"]
categories = ["command-line-utilities"]

[dependencies]
aho-corasick = "1.1.3"
anyhow = "1.0.86"
clap = { version = "4.5.7", features = ["derive", "env"] }
env_logger = "0.11.3"
fs-err = "2.11.0"
log = "0.4.21"
once_cell = "1.19.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_yaml = "0.9.34"
serde_json = "1.0.117"
crypto_box = { version = "0.9.1", features = ["seal", "rand_core", "getrandom"]}
hex = "0.4.3"
sha2 = "0.10.8"
base64 = "0.22.1"

[build-dependencies]
anyhow = "1.0.86"
vergen = { version = "8.3.1", default-features = false, features = ["gitoxide", "git"] }

[dev-dependencies]
assert_cmd = "2.0.14"
tempfile = "3.10.1"

[profile.dev]
# Disabling debug info speeds up builds a bunch,
# and we don't rely on it for debugging that much.
debug = 0

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
